namespace sbh
{
    public static class AppStrings
    {
        //Bydgoszcz 1920 Photos
        public static string Bydgoszcz1920_Photo_1 = "Powitanie pierwszych oddziałów wojska polskiego po wkroczeniu do miasta w dniu 20 stycznia 1920r. Na środku stoi ppłk Witold Butler dowódca oddziału saperów oraz pierwszy wojskowy komendant miasta. Przed nim stoją przedstawiciele władz miasta i Podkomisariatu Naczelnej Rady Ludowej.";
        public static string Bydgoszcz1920_Photo_2 = "Pierwsze oddziały 15 Dywizji Piechoty oraz 16 Pułku Ułanów Wielkopolskich po wkroczeniu na płytę Starego Rynku.";
        public static string Bydgoszcz1920_Photo_3 = "Orkiestra 16 Pułku Ułanów Wielkopolskich podczas defilady na ul. Gdańskiej w dniu 22 stycznia 1920 roku. Defiladę przyjmował dowódca Frontu Wielkopolskiego gen. Józef Dowbor-Muśnicki.";
        public static string Bydgoszcz1920_Photo_4 = "22 stycznia 1920r. Zebrane wojska wielkopolskie na płycie Starego Rynku podczas polowej mszy świętej.";
        public static string Bydgoszcz1920_Photo_5 = "Jan Biziel podczas przemówienia do zebranych mieszkańców miasta w trakcie powitania gen. Józefa Dowbora-Muśnickiego w dniu 22 stycznia 1920r.";
        public static string Bydgoszcz1920_Photo_6 = "Generał Józef Dowbor-Muśnicki w trakcie przemówienia po mszy św. polowej odprawionej na płycie Starego Rynku w dniu 22 stycznia 1920r.";

        //Bydgoszcz 1920 Curiosities
        public static string Bydgoszcz1920_Curiosity_1 = "Od 18 stycznia 1919r. do 21 stycznia 1920 roku trwała Konferencja Pokojowa w Paryżu.\n\n18 lutego 1919r. doszło do potyczki pod Rynarzewem, która zakończyła się zdobyciem niemieckiego pociągu pancernego Panzerzug 22, który następnie został przemianowany na „Danuta”.\n\n20 maja 1919r. do restauracji Sikorskiego znajdującej się przy ul. Gdańskiej wtargnęli członkowie Grenzschutzu i obrzucili granatami znajdujących się we wnętrzu zebranych Polaków.\n\n30 maja 1919r. trzech żołnierzy Grenzschutzu wtargnęło na teren kościoła farnego i obrzucili kamieniami grotę Matki Boskiej z Lourdes.\n\n25 listopada 1919r. podpisano umowę o wycofaniu wojsk z odstąpionych obszarów oraz przekazaniu w ręce polskie zarządu cywilnego nad tymi obszarami.";
        public static string Bydgoszcz1920_Curiosity_2 = "2 sierpnia 1914 r. w Bydgoszczy ogłoszono stan wojenny. Na lazarety zamieniono większość dużych obiektów w mieście, takich jak choćby sale gimnastyczne. Miesiąc od rozpoczęcia wojny w mieście istniało 10 lazaretów. Do końca 1914 roku ten stan powiększono o 100%, w których to lazaretach leczono jednocześnie nawet 3000 rannych żołnierzy.";
        public static string Bydgoszcz1920_Curiosity_3 = "Przygotowania do powitania Wojska Polskiego w Bydgoszczy trwały już od lipca 1919 roku.Prace dekoracyjne w mieście zlecono bydgoskiemu architektowi Teofilowi Biernackiemu.";
        public static string Bydgoszcz1920_Curiosity_4 = "Przed 1 kwietnia 1920 miasto składało się z pięciu zasadniczych części:\nStare Miasto: Miasto, Zamek, Wyspa Młyńska (dawniej Okole), Przedmieście Kujawskie,\nCzęść północna: Ludwikowo(Jachcice), Stacja kolejowa, Bocianowo I (Wielkie), Bocianowo II (Małe), Przedmieście Gdańskie, Grodztwo Zachodnie, Grodztwo Wschodnie, Cmentarze północne, Koszary północne, Koszary leśne, Szkoła wojenna, Boisko sportowe,\nCzęść zachodnia: Okole (dzisiejsze), Koszary ułańskie, Przedmieście Poznańskie,\nCzęść południowa: Szwederowo, Nowy Dwór, Bielice,\nCzęść wschodnia: Przedmieście Toruńskie, Probostwo, Wzgórze Wolności, Żupy\n\nRejony o największej powierzchni to: Grodztwo Wschodnie – 145 ha, Ludwikowo – 63,5 ha, Bocianowo I (Wielkie) – 60 ha.";
        public static string Bydgoszcz1920_Curiosity_5 = "Nocą z 10 na 11 listopada 1918r. w mieście doszło do starcia grupki niemieckich żołnierzy z patrolem Rady Żołnierskiej. Incydent zakończył kilkoma ofiarami śmiertelnymi i kilkoma rannymi. Bunt wśród jednostek bydgoskiego garnizonu rozgorzał najpierw w 14 Pułku Piechoty im. Hrabiego von Schwerin (3 Pomorski).";
        public static string Bydgoszcz1920_Curiosity_6 = "Naczelna Rada Ludowa na miasto Bydgoszcz została powołana 16 listopada 1918 roku. Prezesem został wybrany Jan Biziel, sekretarzem Jan Teska, skarbnikiem Józef Milchert, a członkami zarządu Władysław Kużaj i Antoni Czarnecki.";
        public static string Bydgoszcz1920_Curiosity_7 = "20 maja 1919 r. do restauracji Sikorskiego znajdującej się przy u.Gdańskiej wtargnęli członkowie Grenzschutzu i obrzucili granatami znajdujących się we wnętrzu zebranych Polaków.\n30 maja 1919 r.trzech żołnierzy Grenzschutzu wtargnęło na teren kościoła farnego i obrzucili kamieniami grotę Matki Boskiej z Lourdes.\nOd 18 stycznia 1919 r. do 21 stycznia 1920 roku trwała Konferencja Pokojowa w Paryżu.\n18 lutego 1919 r., doszło do potyczki pod Rynarzewem, która zakończyła się zdobyciem niemieckiego pociągu pancernego Panzerzug 22, który następnie został przemianowany na „Danuta”.\n25 listopada 1919 r.podpisano umowę o wycofaniu wojsk z odstąpionych obszarów oraz przekazaniu w ręce polskie zarządu cywilnego nad tymi obszarami.";
        public static string Bydgoszcz1920_Curiosity_8 = "W nocy z 19 na 20 stycznia 1920r. przemalowano w biało-czerwone barwy wszystkie budki strażnicze stojące przy bramach koszarowych i ważniejszych wojskowych obiektach. Środki na zakup farby pochodziły z licznych zbiórek funduszy, w których hojnie uczestniczyli mieszkańcy Bydgoszczy.";
        public static string Bydgoszcz1920_Curiosity_9 = "W bardzo krótkim czasie Bydgoszcz z typowo pruskiego miasta przerodziła się w pełnoprawną polską metropolię. Jeszcze dziesięć lat wcześniej Bydgoszcz była zamieszkiwana przez 19% Polaków. Według danych z przełomu 1928/1929 r. Polacy stanowili 92% populacji miasta.";
        public static string Bydgoszcz1920_Curiosity_10 = "Bydgoskie więzienie zostało przejęte przez podprokuratora przy Sądzie Okręgowym Jarosława Czarlińskiego oraz prokuratora krajowego Alfreda Jossè.";
        public static string Bydgoszcz1920_Curiosity_11 = "Z gabinetu przeznaczonego dla Prezydenta usunięto portret Fryderyka II i zawieszono obraz przedstawiający poznański ratusz. Oczywiście uczyniono to z powodu braku portretów polskich przywódców, a nie uwielbienia do Poznania.";
        public static string Bydgoszcz1920_Curiosity_12 = "20 stycznia 1920 roku w godzinach przedpołudniowych po ponad wiekowej niewoli w granice miasta wkroczyli pierwsi polscy żołnierze.Na Stary Rynek oddział ppłk.Witolda Butlera  wkroczył wraz z 3 szwadronem 2 Pułku Ułanów Wielkopolskich pod dowództwem rtm.Stanisława Zakrzewskiego punktualnie o godz. 12.00. 22 stycznia 1920r.po uroczystościach na Rynku odbyła się defilada wojsk ulicą Gdańską przed Generałem Muśnickim, który stał na placu Wolności (Weltziena) w otoczeniu swego sztabu i licznej świty.";

        //Bydgoszcz 1920 Media
        public static string Bydgoszcz1920_Media_1 = "W drodze do wolności. Bydgoszcz w 1920 roku";
        public static string Bydgoszcz1920_Media_2 = "Wkroczenie Wojska Polskiego do Bydgoszczy styczeń 1920 rekonstrukcja";
        public static string Bydgoszcz1920_Media_3 = "Makieta Starego Rynku w Bydgoszczy 1920 rok";
        public static string Bydgoszcz1920_Media_4 = "Bydgoszcz100 Tryptyk";

        //Bydgoszcz 1945 Photos
        public static string Bydgoszcz1945_Photo_1 = "W skład zgrupowania „Gneisenau” weszły stacjonujące w Bydgoszczy Szkoła Zwiadu i Kawalerii Bydgoszcz (Aufklärungs und Kavallerieschule Bromberg), wystawiona jako Alarmowy Pułk Wolffien oraz Szkoła Obrony Gazowej Bydgoszcz 2 (Heeresgasschutzschule 2 Bromberg). Alarmowy Pułk Wolffien w sile ok. 600 żołnierzy składał się z 2 Radfahrschwadron, 1 schwere Schwadron i 1 Offizierbewerber Schwadron (OB Schwadron).";
        public static string Bydgoszcz1945_Photo_2 = "W składzie zgrupowania znajdowały się również:\n- Landesschützen-Bataillon 363, który w swoich szeregach posiadał głównie żołnierzy chorych i rannych (Genesenden Kompanie Bromberg), jednakże nadających się do walki oraz żołnierzy pośpiesznie ściąganych z urlopów, którzy nie byli w stanie powrócić do swoich macierzystych jednostek.\n- Volkssturm Bataillon „Zempelburg”, który nie przedstawiał żadnej wartości bojowej.Członkowie tej jednostki uzbrojeni zostali w przestarzałe karabiny głównie pochodzenia francuskiego (Lebel oraz Berthier).\n- Ersatz Grenadier Kompanie Feldernhalle.\n- Polizei Kompanie.\nW leżącym po wschodniej stronie miasta nieodległym Fordonie znajdowała się dodatkowo słaba, bo w sile niepełnego batalionu Szkoła Walki 2 Armii (Armeewaffenschule der 2. Armee) pod dowództwem gen.Rudolfa Noacka (fotografia 1).";
        public static string Bydgoszcz1945_Photo_3 = "Na przedpolu miasta wykonano dwie prowizoryczne linie okopów. W ich powstaniu udział mieli mieszkańcy Bydgoszczy, którzy byli wysyłani w teren do przymusowych prac ziemnych. Już w samym mieście umocniono niektóre obiekty, jako punkty oporu. Wśród nich znalazły się zabudowania Rzeźni Miejskiej, Teatr Miejski, Szpital Garnizonowy i gmach Dyrekcji Kolei. Wykonano również zaminowania niektórych obiektów oraz mostów, w tym mostu przez Wisłę w Fordonie. Jego zniszczenie zależało od bezpośredniej decyzji gen. Heinza Guderiana ówczesnego  Szefa Sztabu  Naczelnego Dowództwa Wojsk Lądowych.";
        public static string Bydgoszcz1945_Photo_4 = "Operacja wiślańsko-odrzańska jak została nazwana w sztabie Naczelnego Dowództwa Armii Czerwonej rozpoczęła się 12 stycznia 1945 r. Wojska Sowieckie uformowano w dwa fronty, które odpowiadały niemieckim Grupom Armii: 1 Front Białoruski oraz 1 Front Ukraiński. Oba fronty były wspomagane przez polskie jednostki z 1 i 2 Armii Wojska Polskiego. Rosjanie przyjęli prostą taktykę, którą umożliwiała im spora przewaga w sprzęcie i zasobach ludzkich. Silniejsze zgrupowania przeciwnika okrążano prąc dalej na zachód i licząc na ich poddanie się, wynikające z beznadziejnej sytuacji, bądź powolną likwidację w późniejszym terminie.";
        public static string Bydgoszcz1945_Photo_5 = "Pułkownik Paul Wuth musiał zareagować niemal błyskawicznie. W rejon ataku rosyjskich czołgów skierowany został Landesschützen-Bataillon 363. Pomimo iż ta jednostka nie przedstawiała większej wartości bojowej to jednak uzbrojona w pancerfausty przyczyniła się do zatrzymania natarcia niszcząc kilka czołgów radzieckich, ponosząc jedynie minimalne straty. Dodatkowo jeden z atakujących czołgów wpadł do śluzu kanału Bydgoskiego znajdującej się przy ul. Bronikowskiego.";
        public static string Bydgoszcz1945_Photo_6 = "Rankiem 23 stycznia Rosjanie zajęli Mroczę na północ od Nakła. Jak się okazało, był to sukces krótkotrwały gdyż miasto w trakcie dwugodzinnej walki zostało odbite przez 15 batalion fizylierów Waffen-SS oraz II batalion 34 Pułku Grenadierów Waffen-SS, wchodzącego w skład podążającej z Bytomia 15 Dywizji Grenadierów Waffen-SS. Straty Rosjan były znaczne. Odnotowano śmierć 30 oraz wzięcie do niewoli 120 żołnierzy przy swoich stratach w postaci zabitych i rannych 14 żołnierzy.";
        public static string Bydgoszcz1945_Photo_7 = "Rotmistrz Hans Roggemann ze Szkoły Zwiadu i Kawalerii. Dowodził oddziałem broniącym dojścia do miasta.";

        //Bydgoszcz 1945 Curiosities
        public static string Bydgoszcz1945_Curiosity_1 = "W celu obrony Bydgoszczy sformowano zgrupowanie „Gneisenau”. W jego skład weszły stacjonujące w Bydgoszczy Szkoła Zwiadu i Kawalerii Bydgoszcz (Aufklärungs und Kavallerieschule Bromberg), wystawiona jako Alarmowy Pułk Wolffien oraz Szkoła Obrony Gazowej Bydgoszcz 2 (Heeresgasschutzschule 2 Bromberg). Alarmowy Pułk Wolffien w sile ok. 600 żołnierzy składał się z 2 Radfahrschwadron, 1 schwere Schwadron i 1 Offizierbewerber Schwadron (OB Schwadron).";
        public static string Bydgoszcz1945_Curiosity_2 = "Operacja „wiślańsko-odrzańska” jak została nazwana w sztabie Naczelnego Dowództwa Armii Czerwonej rozpoczęła się 12 stycznia 1945 r. Wojska Sowieckie uformowano w dwa fronty, które odpowiadały niemieckim Grupom Armii: 1 Front Białoruski oraz 1 Front Ukraiński. Oba fronty były wspomagane przez polskie jednostki z 1 i 2 Armii Wojska Polskiego. Rosjanie przyjęli prostą taktykę, którą umożliwiała im spora przewaga w sprzęcie i zasobach ludzkich. Silniejsze zgrupowania przeciwnika okrążano prąc dalej na zachód i licząc na ich poddanie się, wynikające z beznadziejnej sytuacji, bądź powolną likwidację w późniejszym terminie.";
        public static string Bydgoszcz1945_Curiosity_3 = "W leżącym po wschodniej stronie miasta nieodległym Fordonie znajdowała się dodatkowo słaba, bo w sile niepełnego batalionu Szkoła Walki 2 Armii (Armeewaffenschule der 2. Armee) pod dowództwem gen. Rudolfa Noacka.";
        public static string Bydgoszcz1945_Curiosity_4 = "Rankiem 23 stycznia Rosjanie zajęli Mroczę na północ od Nakła. Jak się okazało, był to sukces krótkotrwały gdyż miasto w trakcie dwugodzinnej walki zostało odbite przez 15 batalion fizylierów Waffen-SS oraz II batalion 34 Pułku Grenadierów Waffen-SS, wchodzącego w skład podążającej z Bytomia 15 Dywizji Grenadierów Waffen-SS. Straty Rosjan były znaczne. Odnotowano śmierć 30 oraz wzięcie do niewoli 120 żołnierzy przy swoich stratach w postaci zabitych i rannych 14 żołnierzy.";

        //Bydgoszcz 1945 Media
        public static string Bydgoszcz1945_Media_1 = "Inscenizacja wyzwolenia";
        public static string Bydgoszcz1945_Media_2 = "Defilada w 1945 roku";
        public static string Bydgoszcz1945_Media_3 = "Styczniowa ofensywa 1945";
        public static string Bydgoszcz1945_Media_4 = "Bydgoszcz 1945";
        
        //Marian Rejewski Photos
        public static string MarianRejewski_Photo_1 = "Marian Adam Rejewski urodził się 16 sierpnia 1905r. w Bydgoszczy. Jego matka, Matylda z domu Thoms, pochodziła z rodziny właścicieli browaru w Podgórzu pod Toruniem. Ojciec, Józef, wywodził się ze zubożałego ziemiaństwa wielkopolskiego spod Gniezna. Po usamodzielnieniu się zamieszkał w Bydgoszczy, został dobrze prosperującym kupcem branży tytoniowej. Był również działaczem społecznym; angażował się w walkę polskich mieszkańców Bydgoszczy z germanizacyjną polityką zaborcy.";
        public static string MarianRejewski_Photo_2 = "Marian był najmłodszym dzieckiem w rodzinie. Miał sześcioro rodzeństwa: trzy siostry i trzech braci. Rejewscy mieszkali w Bydgoszczy w kamienicy przy ul. Wileńskiej 6. Będąc niezależnymi finansowo, posyłali dzieci do najlepszych szkół. W latach 1912 – 1915 Marian uczęszczał do szkoły elementarnej przy Miejskiej Szkole Realnej w Bydgoszczy.";
        public static string MarianRejewski_Photo_3 = "Następnie uczył się w Królewskim Gimnazjum Fryderyka Wilhelma (Königliches Friedrich­Wilhelm Gymnasium in Bromberg), którego ceglany gmach wznosił się u zbiegu Weltzienplatz i Gymnasialstrasse (dzisiaj w tym samym budynku przy placu Wolności i ul. Gimnazjalnej znajduje się I Liceum Ogólnokształcące im. Cypriana Kamila Norwida). 19 stycznia 1920r. w następstwie postanowień traktatu wersalskiego Bydgoszcz wróciła w granice odrodzonego państwa polskiego. W kolejnych dniach Polacy podporządkowali sobie wszystkie urzędy i instytucje. Szkołę, do której uczęszczał Rejewski, przemianowano na Państwowe Gimnazjum Klasyczne i zaczęto polonizować. Był to proces długotrwały i trudny, ponieważ brakowało wykwalifikowanej polskiej kadry nauczycielskiej, która byłaby w stanie prowadzić zajęcia na dotychczasowym wysokim poziomie.";
        public static string MarianRejewski_Photo_4 = "W 1921r., a więc w okresie nauki Mariana w gimnazjum, zmarł jego ojciec. Zarządzanie domem spadło całkowicie na matkę. Źródłem utrzymania rodziny stał się prowadzony przez nią przy ul. Dworcowej punkt loterii fantowej oraz odziedziczony po mężu sklep tytoniowy. Marian był solidnym, ale raczej przeciętnym uczniem. Niczym się jeszcze nie wyróżniał, choć już wówczas ujawniła się jego skłonność ku przedmiotom ścisłym, zwłaszcza matematyce. Pokazują to oceny na świadectwie maturalnym, które otrzymał w 1923r. Z przedmiotów humanistycznych miał stopnie dobre i dostateczne, lecz z przedmiotów ścisłych – bardzo dobre. Zainteresowania te wpłynęły zapewne na wybór kierunku studiów, które rozpoczął w tym samym roku.";
        public static string MarianRejewski_Photo_5 = "Studiował matematykę na Wydziale Matematyczno­-Przyrodniczym Uniwersytetu Poznańskiego. Jego opiekunem naukowym był znany matematyk prof. Zdzisław Krygowski, który szybko dostrzegł talent drzemiący w młodym studencie. Tematem pracy magisterskiej Rejewskiego było „Opracować teorię funkcji podwójnie periodycznych drugiego i trzeciego rodzaju oraz wykazać jej zastosowanie”. Obronił ją 1 marca 1929r. z wynikiem bardzo dobrym, zdobywając tytuł magistra filozofii w zakresie matematyki.";
        public static string MarianRejewski_Photo_6 = "Po II Wojnie Światowej do kraju powrócił 21 listopada 1946r. na pokładzie jednego ze statków pasażerskich. Wysiadł w porcie w Gdyni i pociągiem udał się do Bydgoszczy, gdzie przebywała jego żona z dziećmi. Mieszkała tam u swoich rodziców, w kamienicy przy ul. Dworcowej 10. Wojnę spędziła w stolicy, z której została jednak wysiedlona po upadku powstania warszawskiego.";
        public static string MarianRejewski_Photo_7 = "Niektóre dokumenty sugerują, że Rejewski zamierzał powrócić do opanowanej przez komunistów Polski tylko na chwilę, aby wywieźć z niej rodzinę. W ankiecie personalnej z 6 września 1946r. napisał, że chciałby osiedlić się z rodziną we Francji i zajmować się tam matematyką ubezpieczeniową. Plany te okazały się nierealne. Komuniści nie zezwalali na wyjazd z kraju osób związanych z przedwojennymi władzami, walczących w czasie wojny na Zachodzie. Nielegalne przekroczenie granicy byłoby niebezpieczne, a w towarzystwie żony i małych dzieci wręcz niewykonalne. Rejewski – mający wówczas 41 lat – musiał zaczynać wszystko od nowa. Rodzinę udało się dość szybko poskładać. W dalszej kolejności czekało uporządkowanie spraw zawodowych. Próbował zatrudnić się na Uniwersytecie Poznańskim lub Politechnice Szczecińskiej, jednak – mimo wstawiennictwa prof. Krygowskiego – bezskutecznie. Na przeszkodzie stanął brak stopnia naukowego oraz własnego mieszkania. Zmuszony został do poszukiwania pracy w Bydgoszczy. Od 1 lutego 1947r. zatrudniono go na stanowisku kierownika sekcji fakturowej w fabryce Kabel Polski (po upaństwowieniu w grudniu 1948r. zmieniła ona nazwę na Pomorskie Zakłady Wytwórcze Materiałów Elektrotechnicznych w Bydgoszczy). Życie zaczęło się pomału stabilizować, gdy nagle małżeństwo Rejewskich doświadczyło tragedii. 9 lipca 1947r. w wyniku powikłań związanych z chorobą Heinego­Medina zmarł ich jedenastoletni syn Andrzej. 28 stycznia 1950r. Rejewski został zwolniony z pracy. Był to skutek prowadzonej przez Urząd Bezpieczeństwa Publicznego inwigilacji pracowników bydgoskich zakładów przemysłowych, którzy przed wojną związani byli z wojskiem lub „dwójką”. Sprawę tę oznaczono kryptonimem „Sztab”. Oskarżano ich o kontakty z obcymi służbami, dywersję ideologiczną, propagowanie wrogich wobec władz komunistycznych poglądów, a nawet sabotaż gospodarczy. Nie mając dostatecznych dowodów na popełnienie zarzucanych im czynów, zmuszono ich do zmiany miejsc pracy. Ze znalezieniem zatrudnienia Rejewski nie miał problemu, ponieważ oceniany był jako bardzo dobry fachowiec, sumiennie wykonujący obowiązki. Pracował jako urzędnik, pełniąc również funkcje kierownicze, w Związku Mierniczych w Bydgoszczy (1950–1951), Związku Branżowym Spółdzielni Drzewnych i Wytwórczości Różnej (1951–1954) oraz Wojewódzkim Związku Spółdzielni Pracy (1954–1967). Karierę zawodową zakończył w lutym 1967r., gdy przeszedł na rentę, a potem 16 sierpnia 1970r. na emeryturę.";

        //Marian Rejewski Curiosities
        public static string MarianRejewski_Curiosity_1 = "Marian Adam Rejewski, pseud. Pierre Ranaud (1905–1980), matematyk, kryptolog, autor rozwiązania niemieckiego szyfru maszynowego «Enigma». Urodzony 16.08 w Bydgoszczy, był najmłodszym spośród siedmiorga dzieci Józefa - kupca tytoniowego i Matyldy z domu Thoms. Po zdaniu matury w gimnazjum klasycznym w Bydgoszczy (1923), R. odbył studia matematyczne na Uniw. Pozn. i uzyskał stopień magistra filozofii (1929). W l. 1929–30 specjalizował się. na uniwersytecie w Getyndze w zagadnieniach matematyki ubezpieczeniowej. W latach 1930–32 był młodszym asystentem w Instytucie Matematycznym Uniwersytetu Poznoznańskiego u Zdzisława Krygowskiego. Jednocześnie powołano go do współpracy w poznańskiej ekspozyturze Biura Szyfrów Sztabu Głównego WP, utajnionej komórki wywiadowczo-informacyjnej dla potrzeb rozpoznania sytuacji Polski w odniesieniu do działań państw ościennych, głównie Niemiec.";
        public static string MarianRejewski_Curiosity_2 = "We wrześniu 1932 został Rejewski zaangażowany do stałej pracy w Biurze Szyfrów Oddziału II Sztabu Głównego w Warszawie (odpowiedni kurs odbył tam jeszcze w r. 1929) w Sekcji BS 4 (wywiadu na Niemcy), kierowanej przez kpt. Maksymiliana Ciężkiego. Szef biura mjr Gwido Langer i M. Ciężki byli zaangażowani w akcję rozwiązania tajemnicy niemieckiej maszyny szyfrującej «Enigmy», uznawanej za uniwersalną i rzekomo niezawodną w przekazywaniu tajnych meldunków z możliwością przekazywania tych samych informacji w astronomicznej liczbie kombinacji literowych i zaszyfrowanych wielokrotnie. Rejewski zajął się w BS 4 sprawą «Enigmy» i posłużył się oryginalną metodą kombinatoryki matematycznej, nie stosowaną dotychczas w kryptologii, czyli teorią permutacji (podstawień); opisał ją później w „Applicatione Mathematicae” i in. publikacjach poświęconych przekształceniom zbiorów liczbowych w sposób uporządkowany. Wykorzystanie przez Rejewskiego teorii permutacji doprowadziło go szybko do odkrycia zasady teoretycznej działania «Enigmy» i znalezienia metody odtwarzania kluczy depesz, wielokrotnie zmienianych w tzw. nastawach kodowych a liczących miliony kombinacji. Sukces ten osiągnął też Rejewski dzięki dwu dokumentom niemieckim dostarczonym przez G. Bertranda z francuskiego wywiadu, które pomogły mu zrekonstruować wewnętrzne połączenia «Enigmy»; jej możliwości szyfrowania odpowiadały współczesnym komputerom dużej mocy. Pomyślne wyniki w dekryptażu niemieckiej «Enigmy», osiągnięte na początku r. 1933 wpłynęły wyraźnie na rozwinięcie dalszych prac w tym zakresie, zwłaszcza przy współudziale Jerzego Różyckiego i Henryka Michała Zygalskiego. Tekst ze stycznia 1938r. polscy kryptolodzy odczytywali w Ośrodku BS 4 (krypt. Wicher) ok. 75% zaszyfrowanych materiałów depeszowych, przekazywanych przez polskie ośrodki radiowo-wywiadowcze z całego kraju, a do końca 1938r. tajne informacje z III Rzeszy. Tymczasem wywiady Francji i Anglii nie miały żadnych wówczas wyników w tym zakresie. Rozwiązanie więc w styczniu 1933 szyfru «Enigmy» przez Polaków było sukcesem na skalę międzynarodową, ale o tym fakcie opinia publiczna dowiedziała się z książki Bertranda w r. 1973.";
        public static string MarianRejewski_Curiosity_3 = "Działając w ściśle zakonspirowanym Ośrodku Szyfrów BS 4 (Lasy Kabackie w Pyrach pod Warszawą) Rejewski nawiązał kontakt z niektórymi pracownikami technicznymi Wytwórni Radiotechnicznej AVA w Warszawie: inżynierami braćmi Ludomirem i Stanisławem Danilewiczami, Antonim Palluthem i technikiem Edwardem Fokczyńskim, którzy skonstruowali podobną do «Enigmy», polską maszynę szyfrującą «Lacida». Pod kierunkiem Rejewskiego i wg jego pomysłu skonstruowano jeszcze w tym ośrodku inne urządzenia pomocnicze do dekryptażu: cyklometr i bombę kryptograficzną, ułatwiające i przyspieszające odczytywanie szyfrów «Enigmy». W obliczu zagrożenia wojennego polskie władze wojskowe w sierpniu 1939 udostępniły po jednej replice maszyny «Enigma» wywiadom Francji i Anglii; umożliwiło to Anglikom już w czasie wojny stworzenie w Bletlchey Park koło Londynu własnego systemu «Ultra», nieprzerwanie dostarczającego danych o stanie i działalności armii niemieckiej.";
        public static string MarianRejewski_Curiosity_4 = "Po wybuchu drugiej wojny światowej we wrześniu 1939 Ośrodek BS 4 został zniszczony, a R. z ekipą kryptologów ewakuował się przez Rumunię do Francji. Tam został zaangażowany przez płk. G. Bertranda do pracy w sformowanej komórce kryptologiczno-wojskowej, działającej najpierw w Gretz-Armainvillers pod Paryżem (ośrodek «Bruno»), gdzie Polacy utworzyli własną ekipę «Z», która podobnie jak w Polsce zajmowała się łamaniem i odczytywaniem szyfrów niemiekich. Do tego celu zbudowano kilka «Enigm» i cyklometr, zaś Rejewski opracował jako tajny skrypt Metodykę rozwiązywania szyfrów, pomocny w szkoleniu nowo angażowanych adeptów kryptologii. Jesienią 1940 Rejewski otrzymał fikcyjne nazwisko Pierre Ranaud i zapis w dokumencie jako «profesor liceum w Nantes». Po ewakuacji ośrodka «Bruno» Rejewski z ekipą «Z» udał się do francusko-polskiego ośrodka radiowywiadowczego PC-Cadix w Uzes w pobliżu Nimes i Marsylii. Wkrótce ekipa «Z» otrzymała status wydzielonego oddziału Polskich Sił Zbrojnych na Zachodzie i krypt. Ekspozytura 300. W okresie pracy w ośrodku Cadix R. wraz z J. Różyckim i H. Zygalskim złamali kody i szyfry, którymi niemieccy okupanci posługiwali się w łączności telegraficznej. Po wkroczeniu wojsk niemieckich do nie okupowanej dotąd południowej części Francji, na początku listopada 1942 ośrodek Cadix musiał być zlikwidowany, a jego załoga ewakuowana.";
        public static string MarianRejewski_Curiosity_5 = "Wtedy Rejewski i Zygalski znaleźli początkowo schronienie w Cannes i Nicei, po czym udali się w kierunku granicy hiszpańskiej, z zamiarem dotarcia do Anglii. Przejście granicy hiszpańskiej w Pirenejach było niefortunne i obaj, jednakże nie rozpoznani kryptolodzy polscy, złapani 30.01.1943 przez hiszpańską straż graniczną zostali uwięzieni m. in. w Seo de Urgel, Lerida i Miranda del Ebro. Po stopniowej likwidacji obozu w Mirandzie, w końcu lipca 1943 obaj przedostali się przez Portugalię do Gibraltaru i wnet wylądowali w Londynie. Zostali wówczas skierowani do Kinross w Szkocji, umundurowani w polskiej jednostce łączności, zaopatrzeni w legitymacje z przydziałem służbowym do Batalionu Łączności Sztabu Naczelnego Wodza w Boxmoor pod Londynem, gdzie przydzielono ich do tamtejszego ośrodka dekryptażu, noszącego dla niepoznaki nazwę Pluton Eksploatacyjny. Tutaj jednak nie zajmowali się już szyframi «Enigmy» (całość spraw z nimi związanych przejęli Anglicy), lecz łamaniem szyfrów niemieckich formacji SS. Chodziło zarówno o wojska frontowe SS, jak i siły policyjne przeznaczone do zwalczania ruchu oporu. Rozwiązanie tych szyfrów było bardzo istotne dla współdziałania regularnych armii koalicji z partyzantką i podziemiem. Udział Rejewskiego i Zygalskiego w rozwiązaniu szyfru SS był znaczny i umożliwił regularne czytanie przechwycanych depesz radiowych SS, SD, gestapo i innych służb policyjnych Rzeszy. Od września 1943 do września 1944 niewielka stacja «N» polskiej kompanii radiowywiadowczej w Boxmoor (właściwie dwaj tylko kryptolodzy R. i Zygalski oraz trzech praktykantów), rozwiązała i odczytała 3 124 szyfrogramy, w tym wiele długich, wieloczęściowych. Rozwiązywane szyfrogramy były przez nich także przesyłane do brytyjskiego ośrodka radiowywiadowczego w Bletchley Obaj kryptolodzy 10.10.1943 otrzymali stopień podporucznika i pozostawali na swoim stanowisku do końca wojny.";
        public static string MarianRejewski_Curiosity_6 = "Rejewski powrócił do Polski 20.11.1946 i pracował w Bydgoszczy w firmie «Kabel Polski» (3 lata), w przedsiębiorstwie mierniczym (rok) i w Wojewódzkim Związku Spółdzielni Pracy – do czasu otrzymania renty chorobowej w  1967r. W 1969r. przeniósł się do Warszawy i zajmował się zbieraniem wszelkich materiałów dotyczących dziejów «Enigmy» oraz udzielaniem pomocy historykom i autorom książek, artykułów i filmów o tej sprawie. Pozostawał w żywym kontakcie z dawnym swoim szefem francuskiej grupy radiowywiadowczej gen. G. Bertrandem, pierwszym autorem książki o «Enigmie» (1973). Swoje wspomnienia przekazał do Wojskowego Instytutu Historycznego w Warszawie. Napisał artykuł pt. Jak matematycy polscy rozszyfrowali Enigmę („Wiad. Mat.” 1980 nr 1) i rozdział pt. Matematyczne podstawy rozwiązania niemieckiego szyfru maszynowego „Enigma” w książce W. Kozaczuka pt. „W kręgu Enigmy” (W. 1979, Wyd. 2 1986). Stał się bohaterem kilku książek, artykułów i filmów (m. in. filmu fabularnego pt. „Sekret Enigmy”, zrealizowanego w r. 1979 wg scenariusza S. Strumph-Wojtkiewicza i R. Wionczka, w reżyserii R. Wionczka, postać R-ego kreował Tadeusz Borowski). Otrzymał członkostwo honorowe Polskiego Tow. Matematycznego. R. zmarł nagle 13.02.1980 w Warszawie i pochowany został z honorami wojskowymi na cmentarzu Komunalnym (dawnym wojskowym) na Powązkach (kwatera B-39). Odznaczony był Krzyżem Oficerskim Orderu Odrodzenia Polski.";
        public static string MarianRejewski_Curiosity_7 = "Żonaty (od r. 1934) z Ireną z Lewandowskich, miał syna Andrzeja (zmarłego w wieku 11 lat) oraz córkę Janinę (ur. 1939), magistra matematyki, specjalistę programowania maszyn matematycznych, zamężną za inż. Józefem Sylwestrzakiem. Przypomniane po długich latach zasługi R-ego w rozszyfrowaniu tajemnicy «Enigmy» znalazły wreszcie uznanie badaczy i historyków drugiej wojny światowej, zaliczających go do największych przedstawicieli kryptologii, mających wpływ na przebieg i wydarzenia drugiej wojny światowej. W r. 1985 jego imię nadano szkole i ulicy w Bydgoszczy oraz umieszczono tablicę pamiątkową na domu, w którym mieszkał w Bydgoszczy.";

        //Marian Rejewski Media
        public static string MarianRejewski_Media1 = "Sekret Enigmy";
        public static string MarianRejewski_Media2 = "Wybitny kryptolog z Bydgoszczy";
        public static string MarianRejewski_Media3 = "Biografia";
        public static string MarianRejewski_Media4 = "Mariana Rejewskiego wspomina córka";
        public static string MarianRejewski_Media5 = "Tajemnica Enigmy";
        public static string MarianRejewski_Media6 = "Polscy pogromcy Enigmy";
        public static string MarianRejewski_Media7 = "Enigma";
        public static string MarianRejewski_Media8 = "Marian Rejewski uhonorowany w Krakowie";
        public static string MarianRejewski_Media9 = "Audycje Polskiego Radia";

        //ContentType titles
        public static string ContentDescription_Bydgoszcz1920 = "100 lat Bydgoszczy w Polsce";
        public static string ContentDescription_Bydgoszcz1945 = "Wyzwolenie Bydgoszczy 1945r.";
        public static string ContentDescription_MarianRejewski = "Marian Rejewski";

        public static string Main_Introduction = "\n\nAplikacja ma za zadanie przybliżyć ważne wydarzenia z życia Bydgoszczy, które przez lata popadły w zapomnienie. Piękna historia miasta, nietuzinkowe postaci – przyjrzyj się uważnie tym unikalnym zdjęciom, obejrzyj filmy i wysłuchaj muzyki. To wszystko w aplikacji pod nazwą: Sekrety Bydgoskiej Historii. Projekt będzie rozwijał się o kolejne sekrety, więc wróć tu koniecznie.\n \nKrzysztof Drozdowski";
    }
}
